config/routes.rb
Rails.application.routes.draw do
  root 'states#index'
  resources :states do
    resources :cities do
      resources :categories do
        resources :subcategories do
          resources :postings, except: [:destroy, :edit]
        end
      end
    end
  end



  get '/states/:state_id/cities/:city_id/categories/:category_id/subcategories/:subcategory_id/postings/:id/edit' => 'postings#edit'
  put '/states/:state_id/cities/:city_id/categories/:category_id/subcategories/:subcategory_id/postings/:id' => 'postings#update'
  delete '/states/:state_id/cities/:city_id/categories/:category_id/subcategories/:subcategory_id/postings/:id/delete' => 'postings#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :city
  belongs_to :state, foreign_key: :state_id
  has_many :subcategories
  has_many :postings, through: :subcategories
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :categories
  belongs_to :state
  has_many :subcategories, through: :categories
  has_many :postings, through: :subcategories
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :categories
  has_many :subcategories, through: :categories
  has_many :postings, through: :subcategories
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  belongs_to :subcategory
  # belongs_to :category, through: :subcategories
  # belongs_to :location, through: :categories
  before_save :generate_key

  def generate_key
    self.edit_key = SecureRandom.hex
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  has_many :categories, through: :cities
  has_many :subcategories, through: :categories
  has_many :postings, through: :subcategories
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  has_many :postings
  belongs_to :category
  # belongs_to :location, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
  raise ActionController::RoutingError.new('Not Found')
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @state = State.find(params[:state_id])
    @category = Category.find(params[:id])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def show
  end

  def index
    @locations = Location.all
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  def new
    @state = State.find(params[:state_id])
    @city = City.find(params[:city_id])
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:subcategory_id])
    @posting = Posting.new
  end

  def show
    @state = State.find(params[:state_id])
    @city = City.find(params[:city_id])
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:subcategory_id])
    @posting = Posting.find(params[:id])
  end

  def create
    @state = State.find(params[:state_id])
    @city = City.find(params[:city_id])
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:subcategory_id])
    @posting = Posting.new(posting_params)
    if @posting.save
      flash[:notice] = @posting.edit_key
      redirect_to state_city_category_subcategory_posting_path(@state, @city, @category, @subcategory, @posting)
    else
      render 'new'
    end
  end

  def edit
    @state = State.find(params[:state_id])
    @city = City.find(params[:city_id])
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:subcategory_id])
    @posting = Posting.find(id_params)
    if params[:key] == @posting.edit_key
      render 'edit'
    else
      render not_found
    end
  end

  def destroy
    @state = State.find(params[:state_id])
    @city = City.find(params[:city_id])
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:subcategory_id])
    @posting = Posting.find(id_params)
    if params[:key] == @posting.edit_key
      @posting.destroy
      redirect_to '/'
    else
      render not_found
    end
  end

  def update
    @state = State.find(params[:state_id])
    @city = City.find(params[:city_id])
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:subcategory_id])
    @posting = Posting.find(id_params)
    if Posting.update(@posting.id, posting_params)
      redirect_to state_city_category_subcategory_posting_path(@state, @city, @category, @subcategory, @posting)
    else
      render not_found
    end
  end

  private

  def posting_params
    params.require(:posting).permit(:title, :description, :email)
  end

  def id_params
    params.require(:id)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.all
  end

  def show
    @state = State.find(params[:id])
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def show
    @state = State.find(params[:state_id])
    @city = City.find(params[:city_id])
    @subcategory = Subcategory.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/show.html.erb
<%= @category.name %>
<% @category.subcategories.each do |subcat| %>
    <%= link_to subcat.name, state_city_category_subcategory_path(@state, @category.city, @category, subcat) %>
  <% end %>
  <br>

app/views/cities/show.html.erb
<%= @city.name %>
<% @city.categories.each do |category| %>
  <%= link_to category.name, state_city_category_path(@city.state, @city, category) %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/postings/edit.html.erb
<%= form_for([@state, @city, @category, @subcategory, @posting]) do |f| %>

  <% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :value => @posting.title %>
  </p>


  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description, :value => @posting.description%>
  </p>

  <p>
    <%= f.label :email %> <br>
    <%= f.email_field :email, :value => @posting.email %>
  </p>

  <p>
    <%= f.submit value:"Edit Post" %>
  </p>

<% end %>

<%= link_to 'DESTROYYYYY', state_city_category_subcategory_posting_path(@state, @city, @category, @subcategory, @posting)+"/delete/?key=" + @posting.edit_key, method: :delete, data: { confirm: 'Are you sure you want to DESTROYYYYYY this posting?' }  %>

app/views/postings/new.html.erb
<%= form_for([@state, @city, @category, @subcategory, @posting])do |f| %>
  <% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>


  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :email %> <br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.submit value:"Make Post" %>
  </p>
<% end %>

app/views/postings/show.html.erb
<h2>Title: <%= @posting.title %></h2><br>

<p>Description: <%= @posting.description %></p>

<% if flash[:notice] %>
  <div class="notice"><a href=<%=state_city_category_subcategory_posting_url(@state, @city, @category, @subcategory, @posting)+"/edit/?key=" + flash[:notice]%>%><%=state_city_category_subcategory_posting_url(@state, @city, @category, @subcategory, @posting)+"/edit/?key=" + flash[:notice]%></a></div>
  <% end %>

app/views/states/index.html.erb
<% @states.each do |state| %>
  <%= state.name %>
  <% state.cities.each do |city| %>

    <%= link_to city.name, state_city_path(state, city) %>
  <% end %>
  <br>
<% end %>

app/views/states/show.html.erb
<%= @state.name %>
<% @state.cities.each do |city| %>
    <%= link_to city.name, state_city_path(@state, city) %>
  <% end %>
  <br>

app/views/subcategories/show.html.erb
<%= @subcategory.name %>

<% @subcategory.postings.each do |posting| %>
  <%= link_to posting.title, state_city_category_subcategory_posting_path(@state, @city, @subcategory.category, @subcategory, posting) %>
<% end %>

<%= link_to "New Post", new_state_city_category_subcategory_posting_path(@state, @city, @subcategory.category, @subcategory) %>